#!/usr/bin/python

# iScanner lets you detect Linux malware from your server.
#
# Copyright (C) 2014 iSecur1ty LTD <iscanner@isecur1ty.org>.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# usage [./ui_login.py username password]

import web,hashlib,sys
from web_config import *
from termcolor import *
if len(sys.argv) <=2:
 print "usage ./ui_login username password"
 sys.exit()
new_username = sys.argv[1]
new_password = hashlib.md5(sys.argv[2]).hexdigest()
try:
	db = web.database(dbn='mysql', db=mysql_db, user=mysql_user, pw=mysql_pass)
	db.update('ADMIN', where='id = 1', username =new_username, password=new_password)
	print "\n"
	cprint("username and password successfully changed\n","blue")
except:
	cprint("there was an Error while trying to change login information\n","red")
